### ISSUE TITLE
NavBar Either too small without viewport head or Aboutme Card Exceeds Navbar edge

### ISSUE THREAD

**Issue by juanlajara** [juanlajara/juanlajara.github.io#1]
NavBar Either too small without viewport head or Aboutme Card Exceeds Navbar edge

**Comment by antoniojgage** [comment]
Give me some screenshots of what’s happening and what you want to happen

**Comment by juanlajara** [comment]
@antoniojgage 

![Untitled_ May 16, 2020 11_38 AM](https://user-images.githubusercontent.com/54958540/82125703-6205d400-976d-11ea-900a-968eb5d7bbc2.gif)

**Comment by antoniojgage** [comment]
@juanlajara Trying to make a PR to your branch but 2 things you're right on the meta here is the documentation. The second part is your picture needs to follow the container=> row=> col breakdown 

https://getbootstrap.com/docs/4.5/getting-started/introduction/#responsive-meta-tag

![image](https://user-images.githubusercontent.com/7440005/82127248-a4cca980-9777-11ea-9c20-e29869377d53.png)
